import type { Locale } from "./i18n.ts";

const COMMONMARK_URL = "https://spec.commonmark.org/0.31.2/";
const DEMO_IMAGE = "favicon.svg";

const EN_DEMO = [
  "---",
  "title: Typora-Web demo",
  "status: beta",
  "appearance: light and dark",
  "---",
  "",
  "# Typora-Web demo",
  "",
  "A native, framework-free Markdown editor for the web. It renders rich syntax in place, keeps Markdown round-trippable, and exposes the same document through rendered and source modes.",
  "",
  "[toc]",
  "",
  "## 1. Editor workflow",
  "",
  "- [x] Open, save, and save-as local `.md` files from the File menu.",
  "- [x] Open a local folder tree when the browser supports the File System Access API.",
  "- [x] Toggle source mode with `Ctrl+/`, focus mode with `F8`, and typewriter mode with `F9`.",
  "- [x] Use the sidebar for the file tree and outline; the outline follows the current heading while you scroll.",
  "- [ ] Try editing this document. After your first edit, language switching no longer replaces your content.",
  "",
  "Use `Shift-Enter` for a hard break  ",
  "without leaving the current paragraph. A plain line wrap stays a soft break.",
  "",
  "> Source markers fade when the cursor leaves them, but the underlying Markdown stays editable.",
  "",
  "## 2. Document structure",
  "",
  "### ATX headings",
  "",
  "Headings from `#` through `######` are supported and feed the generated outline.",
  "",
  "Setext heading",
  "---",
  "",
  "Paragraphs, soft breaks, hard breaks, blockquotes, thematic breaks, and HTML comments are preserved.",
  "",
  "<!-- This comment is preserved in Markdown and rendered as an editor hint. -->",
  "",
  "---",
  "",
  "## 3. Inline syntax",
  "",
  "Common inline Markdown works with Typora extensions: **bold**, *italic*, ***bold italic***, ~~strikethrough~~, ==highlight==, <u>underline</u>, H~2~O, x^2^, `inline code`, :smile:, and inline math $a^2 + b^2 = c^2$.",
  "",
  "Links include [inline links](https://github.com/Albert-PZY/typora-web), [reference links][commonmark], angle autolinks <https://example.com>, bare URLs https://spec.commonmark.org/0.31.2/, and email autolinks <hello@example.com>.",
  "",
  "Images render inline. Use Typora-compatible HTML when an explicit display size is needed:",
  "",
  `<img src="${DEMO_IMAGE}" alt="Typora-Web logo" width="96" />`,
  "",
  `Plain Markdown image syntax stays supported too: \`![Typora-Web logo](${DEMO_IMAGE})\`.`,
  "",
  "Backslash escapes keep punctuation literal, for example \\*not italic\\* and \\[not a link\\].",
  "",
  "## 4. Lists and tasks",
  "",
  "1. Ordered lists preserve numbering.",
  "2. Nested content stays editable:",
  "   - Bullet list item",
  "   - Another item with `inline code`",
  "3. Task markers render as checkboxes:",
  "   - [x] Completed task",
  "   - [ ] Pending task",
  "",
  "## 5. Tables",
  "",
  "| Syntax | Example | Status |",
  "|:---|:---:|---:|",
  "| Alignment | left / center / right | Supported |",
  "| Inline marks | **bold**, `code`, ==mark== | Supported |",
  "| Round trip | Markdown stays serializable | Supported |",
  "",
  "## 6. Callouts",
  "",
  "> [!NOTE]",
  "> Notes are neutral information.",
  "",
  "> [!TIP]",
  "> Tips are small suggestions.",
  "",
  "> [!IMPORTANT]",
  "> Important blocks mark required attention.",
  "",
  "> [!WARNING]",
  "> Warnings flag risky operations.",
  "",
  "> [!DANGER]",
  "> Danger blocks highlight severe risk.",
  "",
  "## 7. Code, math, diagrams, and HTML",
  "",
  "```ts",
  "type EditorMode = \"focus\" | \"typewriter\" | \"source\";",
  "",
  "const enabledModes: EditorMode[] = [\"focus\", \"typewriter\"];",
  "",
  "for (const mode of enabledModes) {",
  "  console.log(`Typora-Web keeps ${mode} mode native`);",
  "}",
  "```",
  "",
  "$$",
  "\\int_{0}^{1} x^2\\,dx = \\frac{1}{3}",
  "$$",
  "",
  "```mermaid",
  "flowchart LR",
  "  A[Markdown source] --> B[CommonMark parser]",
  "  B --> C[ProseMirror document]",
  "  C --> D[Typora-style preview]",
  "  D --> E[Markdown serializer]",
  "```",
  "",
  "<details>",
  "<summary>Sanitized HTML preview</summary>",
  "<p><strong>HTML blocks render as safe preview</strong>; click the rendered block to reveal and edit the source.</p>",
  "</details>",
  "",
  "## 8. Compatibility catalog",
  "",
  "Open the Specs page for executable behavior cases. The demo above is a compact tour; specs are the source of truth for edge cases.",
  "",
  "[CommonMark reference][commonmark]",
  "",
  `[commonmark]: ${COMMONMARK_URL}`,
].join("\n");

const ZH_DEMO = [
  "---",
  "title: Typora-Web 中文演示",
  "status: beta",
  "appearance: light and dark",
  "---",
  "",
  "# Typora-Web 中文演示",
  "",
  "这是一个原生、无前端框架的网页 Markdown 编辑器。它会在编辑时原地渲染富语法，同时保持 Markdown 可往返序列化，并支持渲染视图和源码视图切换。",
  "",
  "[toc]",
  "",
  "## 1. 编辑流程",
  "",
  "- [x] 在文件菜单中打开、保存、另存为本地 `.md` 文件。",
  "- [x] 浏览器支持 File System Access API 时，可以打开本地文件夹树。",
  "- [x] 使用 `Ctrl+/` 切换源码模式，`F8` 切换专注模式，`F9` 切换打字机模式。",
  "- [x] 侧边栏支持文件树和大纲；滚动文档时，大纲会跟踪当前标题。",
  "- [ ] 试着编辑这份文档。首次编辑之后，切换语言不会再替换你的内容。",
  "",
  "使用 `Shift-Enter` 插入硬换行  ",
  "并继续留在当前段落。普通换行会保留为软换行。",
  "",
  "> 当光标离开源码标记时，标记会弱化显示，但底层 Markdown 仍然可编辑。",
  "",
  "## 2. 文档结构",
  "",
  "### ATX 标题",
  "",
  "支持 `#` 到 `######` 六级标题，并会进入自动生成的大纲。",
  "",
  "Setext 标题",
  "---",
  "",
  "段落、软换行、硬换行、引用块、分隔线和 HTML 注释都会被保留。",
  "",
  "<!-- 这条注释会保留在 Markdown 中，并显示为编辑器提示。 -->",
  "",
  "---",
  "",
  "## 3. 行内语法",
  "",
  "常见 Markdown 行内语法和 Typora 扩展都可用：**加粗**、*斜体*、***加粗斜体***、~~删除线~~、==高亮==、<u>下划线</u>、H~2~O、x^2^、`行内代码`、:smile:，以及行内数学 $a^2 + b^2 = c^2$。",
  "",
  "链接包括 [行内链接](https://github.com/Albert-PZY/typora-web)、[引用链接][commonmark]、尖括号自动链接 <https://example.com>、裸 URL https://spec.commonmark.org/0.31.2/，以及邮箱自动链接 <hello@example.com>。",
  "",
  "图片会原地渲染。需要指定显示尺寸时，可以使用 Typora 兼容的 HTML 写法：",
  "",
  `<img src="${DEMO_IMAGE}" alt="Typora-Web 标志" width="96" />`,
  "",
  `标准 Markdown 图片语法也仍然支持：\`![Typora-Web 标志](${DEMO_IMAGE})\`。`,
  "",
  "反斜杠转义可以保留标点原义，例如 \\*不是斜体\\* 和 \\[不是链接\\]。",
  "",
  "## 4. 列表和任务",
  "",
  "1. 有序列表会保留编号。",
  "2. 嵌套内容仍然可编辑：",
  "   - 无序列表项",
  "   - 带 `行内代码` 的另一个条目",
  "3. 任务标记会渲染为复选框：",
  "   - [x] 已完成任务",
  "   - [ ] 待完成任务",
  "",
  "## 5. 表格",
  "",
  "| 语法 | 示例 | 状态 |",
  "|:---|:---:|---:|",
  "| 对齐 | 左 / 中 / 右 | 已支持 |",
  "| 行内标记 | **加粗**、`代码`、==高亮== | 已支持 |",
  "| 往返序列化 | Markdown 保持可序列化 | 已支持 |",
  "",
  "## 6. 提示框",
  "",
  "> [!NOTE]",
  "> NOTE 用于普通信息。",
  "",
  "> [!TIP]",
  "> TIP 用于小建议。",
  "",
  "> [!IMPORTANT]",
  "> IMPORTANT 用于必须注意的内容。",
  "",
  "> [!WARNING]",
  "> WARNING 用于需要谨慎的操作。",
  "",
  "> [!DANGER]",
  "> DANGER 用于严重风险。",
  "",
  "## 7. 代码、公式、图表和 HTML",
  "",
  "```ts",
  "type EditorMode = \"focus\" | \"typewriter\" | \"source\";",
  "",
  "const enabledModes: EditorMode[] = [\"focus\", \"typewriter\"];",
  "",
  "for (const mode of enabledModes) {",
  "  console.log(`Typora-Web keeps ${mode} mode native`);",
  "}",
  "```",
  "",
  "$$",
  "\\int_{0}^{1} x^2\\,dx = \\frac{1}{3}",
  "$$",
  "",
  "```mermaid",
  "flowchart LR",
  "  A[Markdown 源码] --> B[CommonMark 解析器]",
  "  B --> C[ProseMirror 文档]",
  "  C --> D[Typora 风格预览]",
  "  D --> E[Markdown 序列化]",
  "```",
  "",
  "<details>",
  "<summary>已消毒的 HTML 预览</summary>",
  "<p><strong>HTML 块会安全渲染预览</strong>；点击渲染区域即可展开并编辑源码。</p>",
  "</details>",
  "",
  "## 8. 兼容性目录",
  "",
  "打开规格页面可以查看可执行的行为用例。上面的示例是紧凑导览；规格才是边界行为的事实来源。",
  "",
  "[CommonMark 参考][commonmark]",
  "",
  `[commonmark]: ${COMMONMARK_URL}`,
].join("\n");

const DEMO_MARKDOWN: Record<Locale, string> = {
  en: EN_DEMO,
  zh: ZH_DEMO,
};

const MINIMAL_DEMO_MARKDOWN: Record<Locale, string> = {
  en: "# Typora-Web demo\n\nMinimal debug content.",
  zh: "# Typora-Web 中文演示\n\n最小化调试内容。",
};

function isMinimalDemo(): boolean {
  if (typeof location === "undefined") return false;
  return location.search.includes("minimal=1") || location.hash.includes("minimal=1");
}

export function getHomeDemoMarkdown(locale: Locale): string {
  if (isMinimalDemo()) return MINIMAL_DEMO_MARKDOWN[locale];
  return DEMO_MARKDOWN[locale];
}
