import type { Locale } from "./i18n.ts";

const EN_DEMO = [
  "---",
  "title: typora-web demo",
  "status: beta",
  "appearance: light and dark",
  "---",
  "",
  "# typora-web demo",
  "",
  "A focused Markdown editing surface that keeps the source round-trippable while rendering rich blocks in place. Try the toolbar above, switch light or dark appearance, then toggle language from the top-right button.",
  "",
  "[toc]",
  "",
  "## Editing flow",
  "",
  "- [x] Open and save local `.md` files from the toolbar.",
  "- [x] Use `Shift-Enter` for hard breaks without leaving the current paragraph.",
  "- [x] Toggle **Focus mode** with `F8` and **Typewriter mode** with `F9`.",
  "- [x] Use common shortcuts such as `Mod-b`, `Mod-i`, `Mod-k`, `Mod-Shift-7`, and `Mod-Shift-8`.",
  "",
  "> Source markers fade when the cursor leaves them, but the Markdown stays editable.",
  "",
  "## Inline syntax",
  "",
  "Typora extensions are supported alongside [CommonMark 0.31.2][commonmark]: ==highlight==, H~2~O, x^2^, ~~removed text~~, `inline code`, :smile:, and inline math $a^2 + b^2 = c^2$.",
  "",
  "Bare URLs become links too: https://spec.commonmark.org/0.31.2/",
  "",
  "## Feature table",
  "",
  "| Feature | Example | Status |",
  "|---|---|---|",
  "| Tables | alignment and inline marks | Complete |",
  "| Task lists | `- [x]` and `- [ ]` | Complete |",
  "| HTML blocks | source-text display | Complete |",
  "| Math | KaTeX inline and block renderers | Complete |",
  "| Diagrams | Mermaid fenced blocks | Complete |",
  "| Code blocks | CodeMirror 6 editor and lazy language loading | Complete |",
  "",
  "## Math",
  "",
  "$$",
  "\\int_{0}^{1} x^2\\,dx = \\frac{1}{3}",
  "$$",
  "",
  "## Mermaid",
  "",
  "```mermaid",
  "flowchart LR",
  "  A[Markdown source] --> B[CommonMark parser]",
  "  B --> C[ProseMirror document]",
  "  C --> D[Typora-style preview]",
  "  D --> E[Markdown serializer]",
  "```",
  "",
  "## Code highlighting",
  "",
  "```ts",
  "type EditorMode = \"focus\" | \"typewriter\" | \"source\";",
  "",
  "const enabledModes: EditorMode[] = [\"focus\", \"typewriter\"];",
  "",
  "for (const mode of enabledModes) {",
  "  console.log(`typora-web keeps ${mode} mode native`);",
  "}",
  "```",
  "",
  "## HTML source block",
  "",
  "<details>",
  "<summary>HTML source stays editable</summary>",
  "<p><strong>HTML blocks stay as source text</strong> so native widgets do not replace the Markdown editing surface.</p>",
  "</details>",
  "",
  "## Notes",
  "",
  "This editor is still beta. The compatibility catalog documents each behavior as an executable spec.",
  "",
  "[CommonMark reference][commonmark]",
  "",
  "[commonmark]: https://spec.commonmark.org/0.31.2/",
].join("\n");

const ZH_DEMO = [
  "---",
  "title: typora-web 中文演示",
  "status: beta",
  "appearance: light and dark",
  "---",
  "",
  "# typora-web 中文演示",
  "",
  "这是一个接近 Typora 体验的 Markdown 编辑界面：源码保持可往返序列化，数学公式、图表、HTML 块和代码高亮会在原地渲染。你可以使用上方工具栏，也可以点击右上角按钮切换亮色、暗色和语言。",
  "",
  "[toc]",
  "",
  "## 编辑流程",
  "",
  "- [x] 通过工具栏打开和保存本地 `.md` 文件。",
  "- [x] 使用 `Shift-Enter` 插入硬换行，并留在当前段落中继续输入。",
  "- [x] 使用 `F8` 切换**专注模式**，使用 `F9` 切换**打字机模式**。",
  "- [x] 使用 `Mod-b`、`Mod-i`、`Mod-k`、`Mod-Shift-7`、`Mod-Shift-8` 等常见快捷键。",
  "",
  "> 当光标离开源码标记时，标记会弱化显示，但 Markdown 源码仍然可编辑。",
  "",
  "## 行内语法",
  "",
  "在 [CommonMark 0.31.2][commonmark] 基线之上，已经支持多种 Typora 扩展：==高亮==、H~2~O、x^2^、~~删除线~~、`行内代码`、:smile:，以及行内数学 $a^2 + b^2 = c^2$。",
  "",
  "裸 URL 也会自动变成链接：https://spec.commonmark.org/0.31.2/",
  "",
  "## 功能表",
  "",
  "| 功能 | 示例 | 状态 |",
  "|---|---|---|",
  "| 表格 | 对齐与行内标记 | 已完成 |",
  "| 任务列表 | `- [x]` 和 `- [ ]` | 已完成 |",
  "| HTML 块 | 按源码文本显示 | 已完成 |",
  "| 数学公式 | KaTeX 行内和块级渲染 | 已完成 |",
  "| 图表 | Mermaid 围栏代码块 | 已完成 |",
  "| 代码块 | CodeMirror 6 编辑器与语言懒加载 | 已完成 |",
  "",
  "## 数学公式",
  "",
  "$$",
  "\\int_{0}^{1} x^2\\,dx = \\frac{1}{3}",
  "$$",
  "",
  "## Mermaid 图表",
  "",
  "```mermaid",
  "flowchart LR",
  "  A[Markdown 源码] --> B[CommonMark 解析器]",
  "  B --> C[ProseMirror 文档]",
  "  C --> D[Typora 风格预览]",
  "  D --> E[Markdown 序列化]",
  "```",
  "",
  "## 代码高亮",
  "",
  "```ts",
  "type EditorMode = \"focus\" | \"typewriter\" | \"source\";",
  "",
  "const enabledModes: EditorMode[] = [\"focus\", \"typewriter\"];",
  "",
  "for (const mode of enabledModes) {",
  "  console.log(`typora-web keeps ${mode} mode native`);",
  "}",
  "```",
  "",
  "## HTML 源码块",
  "",
  "<details>",
  "<summary>HTML 源码保持可编辑</summary>",
  "<p><strong>HTML 块会按源码文本显示</strong>，避免原生控件替代 Markdown 编辑界面。</p>",
  "</details>",
  "",
  "## 备注",
  "",
  "当前项目仍处于 beta 阶段。完整兼容性目录会把每个行为记录成可执行规格。",
  "",
  "[CommonMark 参考][commonmark]",
  "",
  "[commonmark]: https://spec.commonmark.org/0.31.2/",
].join("\n");

const DEMO_MARKDOWN: Record<Locale, string> = {
  en: EN_DEMO,
  zh: ZH_DEMO,
};

export function getHomeDemoMarkdown(locale: Locale): string {
  return DEMO_MARKDOWN[locale];
}
